### PR TITLE
hotfix: fixed the error that shows up in the console for donation confirmation

### LINKED ISSUE #279: console log errors on donate again flow
see gif and console:

Image

```
client.js:2 Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    at button
    at eval 
```

### PR DESCRIPTION
**Pull request by OVECJOE**
In response to the issue #279, the commit and PR were created.

This error was thrown in the console because the close button from Chakra UI was nested inside the dialog close trigger component, which itself seems to be a button.

To fix it, I made the close button a span element inside the trigger.

While at it, I also made the action buttons justified to the end, instead of the center, because it feels aesthetically better there.

### CODE REVIEW

File: components/existingDonationDialog.js [hunk 1]
```diff
@@ -51,7 +51,7 @@ const ExistingDonationDialog = ({
             we'll update it for you to <strong>${newAmount}</strong> from now on.
           </Text>
         </DialogBody>
-        <DialogFooter className='flex justify-center gap-4'>
+        <DialogFooter className='flex justify-end gap-4'>
```
Comment (joelwass) [inline components/existingDonationDialog.js]: lets revert this change, for now lets keep buttons center justified

Comment (OVECJOE) [reply components/existingDonationDialog.js]: Noted.

**Review by joelwass — APPROVED** [review]
